version: '3'

services:
#  mysql:
#    image: mysql:5.7.25
#    container_name: mysql
#    environment:
#      # MYSQL_DATABASE: dataflow
#      MYSQL_USER: root
#      MYSQL_ROOT_PASSWORD: root
#    expose:
#      - 3306

  kafka-broker:
    image: confluentinc/cp-kafka:5.3.1
    container_name: kafka
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka-broker
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: kafka-zookeeper
    expose:
      - "2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  account:
    restart: always
    build: ./account
    working_dir: /account
    volumes:
      - ./account:/account
      - ~/.m2:/root/.m2
    expose:
      - "8081"
    command: mvn clean spring-boot:run
#    depends_on:
#      - hk-mysql