
###


###
POST http://localhost:8082/customers
Content-Type: application/json

{ "name":  "Mike Wazowski"}

###
POST http://localhost:8082/customers/1/cards
Content-Type: application/json

{"number":  "888888", "pin":  "1111"}

###

GET http://localhost:8082/customers/cards/888888
Accept: application/json
pin: 1111

###

